"use client"
import { useState } from "react"
import { useRouter } from "next/navigation"
import { useApp } from "@/context/AppContext"
import AppShell from "@/components/layout/AppShell"
import PageHeader from "@/components/ui/PageHeader"
import Button from "@/components/ui/Button"
import Input from "@/components/ui/Input"
import Select from "@/components/ui/Select"
import Textarea from "@/components/ui/Textarea"
import PhotoUpload from "@/components/ui/PhotoUpload"
import { ArrowLeft, UserCircle } from "lucide-react"
import Link from "next/link"
import type { DominantFoot, Position, Category } from "@/lib/types"
import { avatarUrl } from "@/lib/utils"
import { useT } from "@/lib/i18n/useT"
import { players as playersDict } from "@/lib/i18n/dictionaries/players"
import { useEnumT } from "@/lib/i18n/enums"

const POSITIONS: Position[] = ["Portero","Defensa Central","Lateral Derecho","Lateral Izquierdo","Mediocampista Defensivo","Mediocampista Central","Mediocampista Ofensivo","Extremo Derecho","Extremo Izquierdo","Delantero Centro","Segundo Delantero"]
const CATEGORIES: Category[] = ["Sub-5","Sub-6","Sub-7","Sub-8","Sub-9","Sub-10","Sub-11","Sub-12","Sub-13","Sub-14","Sub-15","Otra"]
const FEET: DominantFoot[] = ["Derecha","Izquierda","Ambidiestro"]

export default function NewPlayerPage() {
  const { addPlayer, currentUser } = useApp()
  const router = useRouter()
  const t = useT(playersDict)
  const e = useEnumT()
  const isAssistant = currentUser?.role === "assistant"
  const [saving, setSaving] = useState(false)
  const [form, setForm] = useState({
    name: "", age: "", birth_date: "", position: "" as Position | "",
    dominant_foot: "" as DominantFoot | "", height: "", weight: "",
    club: "Academia FutbolMetrics", category: (currentUser?.category ?? "") as Category | "",
    objective: "", notes: "", photo_url: "",
  })

  const set = (k: keyof typeof form, v: string) => setForm(f => ({ ...f, [k]: v }))

  const previewAvatar = form.photo_url || (form.name ? avatarUrl(form.name, "new") : "")

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    setSaving(true)
    await new Promise(r => setTimeout(r, 600))
    const player = addPlayer({
      name: form.name,
      age: Number(form.age),
      birth_date: form.birth_date,
      position: form.position as Position,
      dominant_foot: form.dominant_foot as DominantFoot,
      height: Number(form.height),
      weight: Number(form.weight),
      club: form.club,
      category: form.category as Category,
      objective: form.objective,
      notes: form.notes,
      photo_url: form.photo_url || avatarUrl(form.name, "new"),
    })
    router.push(`/players/${player.id}`)
  }

  return (
    <AppShell>
      <div className="p-4 md:p-6 xl:p-8 animate-fade-in max-w-4xl">
        <div className="flex items-center gap-3 mb-6">
          <Link href="/players" className="w-9 h-9 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 flex items-center justify-center text-slate-500 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-800/60 transition-colors">
            <ArrowLeft size={16} />
          </Link>
          <PageHeader title={t("newPlayerTitle")} subtitle={t("newPlayerSubtitle")} className="mb-0 flex-1" />
        </div>

        <form onSubmit={handleSubmit}>
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            {/* Left: Photo */}
            <div className="bg-white dark:bg-slate-900 rounded-2xl p-6 border border-slate-100 dark:border-slate-800 flex flex-col items-center gap-4 h-fit">
              <div className="w-28 h-28 rounded-2xl bg-slate-100 dark:bg-slate-800 overflow-hidden border-2 border-slate-200 dark:border-slate-700 flex items-center justify-center">
                {previewAvatar ? (
                  <img src={previewAvatar} alt="Preview" className="w-full h-full object-cover" />
                ) : (
                  <UserCircle className="w-16 h-16 text-slate-300 dark:text-slate-600" />
                )}
              </div>
              <p className="text-xs text-slate-500 dark:text-slate-400 text-center leading-relaxed">
                {t("avatarAutoGenerated")}
              </p>
              <PhotoUpload folder="players" onUploaded={url => set("photo_url", url)} />
              <Input
                label={t("photoUrlLabel")}
                placeholder="https://..."
                value={form.photo_url}
                onChange={e => set("photo_url", e.target.value)}
                className="w-full text-xs"
              />
            </div>

            {/* Right: Form */}
            <div className="lg:col-span-2 space-y-5">
              {/* Personal info */}
              <div className="bg-white dark:bg-slate-900 rounded-2xl p-6 border border-slate-100 dark:border-slate-800">
                <h3 className="text-sm font-bold text-slate-900 dark:text-white mb-4">{t("personalInfo")}</h3>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div className="sm:col-span-2">
                    <Input label={t("fullNameLabel")} placeholder="Carlos Andrés Martínez" value={form.name} onChange={ev => set("name", ev.target.value)} required />
                  </div>
                  <Input label={t("ageLabel")} type="number" placeholder="17" min={5} max={40} value={form.age} onChange={ev => set("age", ev.target.value)} />
                  <Input label={t("birthDateLabel")} type="date" value={form.birth_date} onChange={ev => set("birth_date", ev.target.value)} />
                  <Input label={t("heightCmLabel")} type="number" placeholder="178" min={100} max={250} value={form.height} onChange={ev => set("height", ev.target.value)} />
                  <Input label={t("weightKgLabel")} type="number" placeholder="72" min={30} max={150} value={form.weight} onChange={ev => set("weight", ev.target.value)} />
                </div>
              </div>

              {/* Sports info */}
              <div className="bg-white dark:bg-slate-900 rounded-2xl p-6 border border-slate-100 dark:border-slate-800">
                <h3 className="text-sm font-bold text-slate-900 dark:text-white mb-4">{t("sportsInfo")}</h3>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <Select
                    label={t("positionLabel")}
                    value={form.position} onChange={ev => set("position", ev.target.value)}
                    placeholder={t("selectPlaceholder")} required
                    options={POSITIONS.map(p => ({ value: p, label: e.position(p) }))}
                  />
                  <Select
                    label={t("dominantFootLabel")}
                    value={form.dominant_foot} onChange={ev => set("dominant_foot", ev.target.value)}
                    placeholder={t("selectPlaceholder")} required
                    options={FEET.map(f => ({ value: f, label: e.dominantFoot(f) }))}
                  />
                  <Select
                    label={t("categoryLabel")}
                    value={form.category} onChange={ev => set("category", ev.target.value)}
                    placeholder={t("selectPlaceholder")} required disabled={isAssistant}
                    options={CATEGORIES.map(c => ({ value: c, label: e.category(c) }))}
                  />
                  <Input label={t("clubLabel")} placeholder="Academia FutbolMetrics" value={form.club} onChange={ev => set("club", ev.target.value)} />
                </div>
              </div>

              {/* Notes */}
              <div className="bg-white dark:bg-slate-900 rounded-2xl p-6 border border-slate-100 dark:border-slate-800">
                <h3 className="text-sm font-bold text-slate-900 dark:text-white mb-4">{t("objectivesAndObservations")}</h3>
                <div className="space-y-4">
                  <Textarea label={t("sportingObjectiveLabel")} placeholder="Llegar al fútbol profesional..." value={form.objective} onChange={ev => set("objective", ev.target.value)} rows={2} />
                  <Textarea label={t("coachObservationsLabel")} placeholder={t("additionalNotesPlaceholder")} value={form.notes} onChange={ev => set("notes", ev.target.value)} rows={2} />
                </div>
              </div>

              <div className="flex items-center gap-3 justify-end">
                <Link href="/players">
                  <Button variant="secondary" type="button">{t("cancel")}</Button>
                </Link>
                <Button type="submit" loading={saving}>
                  {t("createPlayer")}
                </Button>
              </div>
            </div>
          </div>
        </form>
      </div>
    </AppShell>
  )
}
